### ISSUE TITLE
Tutorial shows incorrect path to configs in druid directory

### ISSUE THREAD

**Issue by art4noir** [druid-io/druid-io.github.io#528]
Incorrect path is written in Start up Druid services block - it has parts like
`java 'cat examples/conf/druid/coordinator/jvm.config | xargs' -cp "examples/conf/druid/_common:examples/conf/druid/_common/hadoop-xml:examples/conf/druid/coordinator:lib/*" io.druid.cli.Main server coordinator
`
while there are no directory 'druid-0.12.3/examples/conf' - only druid-0.12.3/conf and  druid-0.12.3/conf-quickstart. 
Incorrect path on command leads to failed launch with unclear stacktrace.

**Comment by jon-wei** [comment]
Did you follow the instructions under "Download tutorial example files" here? http://druid.io/docs/latest/tutorials/index.html

**Comment by art4noir** [comment]
Sorry, seems I missed it. But is it ok to have several configurations for quickstart? I mean 'druid-0.12.3/conf-quickstart' and conf from example packages.

**Comment by jon-wei** [comment]
I don't think it's a huge problem to have a few different files there so long as the tutorial works, but `druid-0.12.3/conf-quickstart` will be gone in 0.13.0. It's there now since this tutorial was added after 0.12.3 was released and we didn't want to repackage or do another release just to include the example files.
